apiVersion: v1
kind: Pod
metadata:
  name: node-api-container
  labels:
    app: node-api-container
spec:
  containers:
    - name: node-api-container
      image: ianmilneuk/node-api-container:development
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 0.3
          memory: 128M		
